Fixing issue with ld: symbol(s) not found for architecture x86_64 * Twitterkit not compiling on latest xcode due to pod provided framework dependancies which is - deprecated